---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{include "attestation-controller.fullname" .}}
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
  annotations: {{- toYaml .Values.route.annotations | nindent 4}}
spec:
  podSelector:
    matchLabels: {{- include "attestation-controller.selectorLabels" . | nindent 6}}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
