---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attestation-controller.fullname" . }}-google-oauth-key
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
type: Opaque
data:
  google_oauth_key.json: {{.Values.google_oauth_key.json | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attestation-controller.fullname" . }}-traction-creds
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
type: Opaque
data:
  TRACTION_TENANT_ID: {{.Values.tenant_id | b64enc}}
  TRACTION_TENANT_API_KEY: {{.Values.tenant_api_key | b64enc}}

