---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attestation-controller.fullname" . }}-google-oauth-key
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
type: Opaque
data:
  google_oauth_key.json: {{.Values.google_oauth_key.json | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attestation-controller.fullname" . }}-traction-creds
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
type: Opaque
data:
  TRACTION_WALLET_ID: {{.Values.wallet_id | b64enc}}
  TRACTION_WALLET_KEY: {{.Values.wallet_key | b64enc}}

