---
apiVersion: v1
kind: Service
metadata:
  name: {{include "attestation-controller.fullname" .}}
  labels: {{- include "attestation-controller.labels" . | nindent 4}}
spec:
  ports:
    - port: {{.Values.service.targetPort}}
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: http
  selector: {{- include "attestation-controller.selectorLabels" . | nindent 4}}
