version: '3.9'

networks:
  local_network:
    name: local_network

services:
  workspace:
    image: python:3-alpine3.19
    working_dir: /work
    volumes:
      - ../:/work
    ports:
      - '8443:8443'
    tty: true
    networks:
      - local_network
