version: "3.9"

networks:
  local_network:
    name: local_network

services:
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    tty: true
    networks:
      - local_network

  workspace:
    image: python:3.8.18-bullseye
    working_dir: /work
    volumes:
      - ../:/work
    ports:
      - "8443:8443"
    tty: true
    networks:
      - local_network
    environment:
      - REDIS_URL=redis://redis:6379/0
