# Default values for attestation-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 6

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

image:
  pullPolicy: Always
  registry: artifacts.developer.gov.bc.ca/docker-remote
  repository: redis
  tag: "7-alpine"

resources:
  requests:
    memory: 64Mi
    cpu: 10m
  limits:
    memory: 128Mi
    cpu: 100m

dataVolumeSize: "32Mi"

imagePullSecrets:
  - name: artifactory-regcred

service:
  - name: gossip
    port: 16379
  - name: redis
    port: 6379

route:
  host: ""
  annotations:
    haproxy.router.openshift.io/timeout: 60s

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: true
#   # Automatically mount a ServiceAccount's API credentials?
#   automount: true
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

