---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  labels: {{- include "redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := .Values.service }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}  
  selector: 
    app.kubernetes.io/component: redis
    {{- include "redis.selectorLabels" . | nindent 4 }}
  